/** Cloud-dwelling characters: no landable surface is implied below them. */
export const GIANT_REMARKS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  jupiter: Object.freeze([
    'I contain multitudes. Mostly lunch.',
    'That cloud looked smaller on the menu.',
    'Large? I prefer extensively charming.',
    'My personal space has its own weather.',
    'Striped skies. Very slimming backdrop.',
    'Great Red Spot. Still not ketchup.',
    'I asked for a cloud with a filling.',
    'A gentle giant. Until the snacks run out.',
    'My table manners need a bigger table.',
    'No seabed. Splendid excuse to drift.',
    'Cloud buffet. Suspiciously all cloud.',
    'I swallowed a cloud. Very airy.',
    'Deep thoughts. Shallow diving budget.',
    'This is my small, discreet entrance.',
    'A planet this big needs a whale on staff.',
    'I have never once fitted in a selfie.',
    'My shadow needs planning permission.',
    'Yes, the cloud has a whale in it.',
    'That storm has more stamina than I do.',
    'I am not lost. I am marinating.',
    'Ten-hour days. Snack often.',
    'Cloud nine was full. I ate cloud eight.',
    'My exercise routine is mostly buoyant.',
    'Small talk takes me several kilometres.',
    'The fog is wearing me beautifully.',
    'Plankton? This menu is wildly unhelpful.',
    'A nap of this size takes preparation.',
    'Please do not feed the ego. Feed me.',
    'My waistline is a local landmark.',
    'I requested a window seat. Got weather.',
    'I am the reason this cloud looks full.',
    'Gravity and I have a weighty history.',
    'Do not mistake my lunch for a moon.',
    'This cloud has excellent elbow room.',
    'There is no floor. I checked with a snack.',
    'I am doing laps. Very generous laps.',
    'Whale-sized portions. Finally, a policy.',
    'The forecast is partly me.',
    'Dignity first. Then second breakfast.',
    'My belly has entered the conversation.',
    'I can keep a secret. And six lunches.',
    'Call me streamlined. Use a large font.',
    'I blend in. With rather large things.',
    'My itinerary says waft, then nibble.',
    'That cloud owes me a biscuit.',
    'The storm can wait. I am chewing.',
    'I make an excellent scenic obstruction.',
    'My singing voice comes with weather.',
    'A little cloud cover? Happy to help.',
    'I leave room for dessert. Lots of room.',
  ]),
  saturn: Object.freeze([
    'Captain speaking. Mostly to myself.',
    'All hands! Both of them, please.',
    'Periscope up. Visibility: beige.',
    'Cloud ahead. Also astern. Busy day.',
    'I run a tight ship. Loose paperwork.',
    'Permission to look important: granted.',
    'Dive plan: avoid the further-down bit.',
    'No seabed. Anchor feeling redundant.',
    'I ordered a berth. They sent a cloud.',
    'Cloud navigation: squint with authority.',
    'The captain has misplaced starboard.',
    'Port is left. Biscuit tin is empty.',
    'Ring road ahead. Several, actually.',
    'Those rings are not parking spaces.',
    'Emergency drill: locate the biscuits.',
    'Log entry: still very much a submarine.',
    'Aye aye. One aye would have done.',
    'Captain on deck. Deck not included.',
    'Submerged in forms. Mostly forms.',
    'Cloud depth: more than I ordered.',
    'The fog has not filed its paperwork.',
    'Periscope cleaned. Cloud still dirty.',
    'No floor. Strictly a floating concern.',
    'Our lifeboat is another poor decision.',
    'I salute. Nobody sees. I salute again.',
    'Uniform crisp. Command of events: floppy.',
    'Steady as she goes. Wherever that is.',
    'One small sub. An admiral-sized ego.',
    'Batten the hatches. Label the battens.',
    'That cloud has ignored my semaphore.',
    'A naval hat makes this official.',
    'Compass checked. Lunch more pressing.',
    'Crew morale: awaiting tea.',
    'The galley serves cloud on toast.',
    'I have promoted the kettle.',
    'Engine room reports a suspicious nap.',
    'Those rings outrank my entire uniform.',
    'I requested clear skies. Request denied.',
    'Do not knock. Use the periscope.',
    'All stations: look vaguely nautical.',
    'I named this cloud HMS Probably.',
    'Captain of all I can almost see.',
    'A foghorn feels a little on the nose.',
    'Map update: added another question mark.',
    'Clouds are terrible at following orders.',
    'The next port is entirely hypothetical.',
    'That hexagon has excellent discipline.',
    'Report any suspiciously solid clouds.',
    'Duty calls. I have put it on hold.',
    'Surfacing requires my best serious face.',
  ]),
  uranus: Object.freeze([
    'Planet sideways. Ticket marked urgent.',
    'Have you tried turning it upright?',
    'Reboot complete. Still chilly.',
    'Thermal plan: acquire second cardigan.',
    'Cold start. Colder everything else.',
    'My warranty excludes this much tilt.',
    'Floor not found. Do not retry.',
    'Ice giant. Ice tray sold separately.',
    'The horizon failed its spirit level.',
    'Upright is a configurable setting.',
    'My circuits are filing a cold complaint.',
    'Heated seats would count as progress.',
    'Processing warmth. No results found.',
    'I brought a ruler. Planet brought tilt.',
    'Cloud storage. Very literal provider.',
    'Please keep feet inside the metaphor.',
    'No hard drive. No hard ground either.',
    'Gravity works. Customer service does not.',
    'I run on logic and borrowed knitwear.',
    'Error: scarf exceeds robot length.',
    'Blue-green. Factory settings, apparently.',
    'My thermostat has requested a transfer.',
    'Tilt detected. I shall also lean.',
    'I have installed a reassuring eyebrow.',
    'Forecast downloaded. Deleted in protest.',
    'The cold is a feature. I prefer bugs.',
    'This cloud has no mounting bracket.',
    'I tightened a bolt. Felt better.',
    'Support request: something to stand on.',
    'I cannot shrug. Consider this a shrug.',
    'Comfort is outside my specifications.',
    'Nice tilt. Did you keep the receipt?',
    'My hot take has reached room temperature.',
    'I calculate, therefore I need mittens.',
    'Wool is a surprisingly good upgrade.',
    'This is my emotionally neutral shiver.',
    'Boots installed. Ground still missing.',
    'A level playing field? Wrong planet.',
    'I asked for cool. Procurement overdid it.',
    'This angle is not covered by the manual.',
    'I am buffering. Please knit quietly.',
    'Optimism module frozen. Logic unbothered.',
    'Cable management: now mostly scarf.',
    'A cloud is not a load-bearing structure.',
    'I made a warm backup. It cooled.',
    'My reset button needs gloves.',
    'Tilt correction exceeds spanner size.',
    'The kettle is my favourite colleague.',
    'My weather app just displays a frown.',
    'Sideways is merely upright elsewhere.',
  ]),
  neptune: Object.freeze([
    'My scarf has a life of its own.',
    'The wind and I are not on scarf terms.',
    'I packed light. The wind packed lighter.',
    'A calm day. By scarf standards.',
    'My hat has applied for independence.',
    'Cold hands. Technically no hands.',
    'I have a carrot. That is my plan.',
    'My nose points bravely downwind.',
    'Stoicism is cheaper than a coat.',
    'I think, therefore I need another scarf.',
    'A snowman of few words. Most blew away.',
    'I knitted a thought. It was chilly.',
    'That gust was unnecessarily personal.',
    'Windproof? The label was optimistic.',
    'No ground. I miss standing for things.',
    'My buttons are holding a small protest.',
    'Ice giant. Snowman not to scale.',
    'I brought mittens. An abstract purchase.',
    'The Sun is trying its distant best.',
    'I would wave. You might lose the arm.',
    'My poker face is mostly packed snow.',
    'There is dignity in a well-tied scarf.',
    'I remain unmelted by your argument.',
    'The breeze has borrowed my silhouette.',
    'I asked for a trim. The wind obliged.',
    'I am my own emergency ice supply.',
    'A stiff upper carrot is essential.',
    'I ponder. The scarf does the panicking.',
    'My hat returns on its own schedule.',
    'I am not sulking. This is my snow face.',
    'Cloud beneath. Existential gap beneath.',
    'The horizon looks cold. It is consistent.',
    'Stillness is an ambitious hobby here.',
    'My scarf is longer than my patience.',
    'Knitting is just organised optimism.',
    'I keep my cool. Very little choice.',
    'Wind: many opinions, no indoor voice.',
    'The forecast has ruined my fringe.',
    'I gave the gale a stern carrot.',
    'My autobiography needs a paperweight.',
    'I lean into life. Mostly the gusts.',
    'A warm welcome would be complicated.',
    'All this cloud. Not one coat hook.',
    'My best side is whichever stays put.',
    'The hat is decorative. The knot is vital.',
    'My buttons are my least frozen assets.',
    'At least my ice cubes are safe.',
    'I travel light. Three lumps, one nose.',
    'I am a very patient weather complaint.',
    'The universe is vast. Knit accordingly.',
  ]),
});
