/** Ambient remarks: each line works before, during, or after a flight.
 * These worlds have solid surfaces. Airless worlds make no sound claims.
 */
export const ROCKY_REMARKS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  earth: Object.freeze([
    'Fore! My entire safety briefing.',
    'I dress like this voluntarily.',
    'The club does most of the apologising.',
    'Par is more of a suggestion.',
    'My handicap is optimism.',
    'I practise my excuses daily.',
    'The trousers are regulation dreadful.',
    'A divot is just a tiny valley.',
    'The grass is judging my technique.',
    'Golf: a walk with extra paperwork.',
    'Blame the club. It expects it.',
    'My caddy has requested a transfer.',
    'The scorecard is mostly fiction.',
    'I am dressed for a much easier game.',
    'A cannon counts as a long iron.',
    'I brought nine clubs and one excuse.',
    'The bunker and I are pen pals.',
    'My swing has several plot twists.',
    'I prefer a generous definition of par.',
    'The green owes me an apology.',
    'My lucky socks are under review.',
    'Technique is just confident fidgeting.',
    'The trophy shelf holds biscuits.',
    'I have a very aerodynamic bald patch.',
    'My membership includes disappointment.',
    'Keep the receipt for that confidence.',
    'The flag has a better stance than me.',
    'The dress code did not mention dignity.',
    'I iron my trousers, never my approach.',
    'My best club is the sandwich club.',
    'The squirrels know my average.',
    'I call this outfit camouflage.',
    'The lawn committee fears me.',
    'My warm-up requires a sit-down.',
    'The tee is my emotional support peg.',
    'I came for golf. I stayed for pudding.',
    'This hat adds nothing to the science.',
    'I have excellent follow-through snacks.',
    'The grass is greener near the cafe.',
    'My club selection is mostly cutlery.',
    'The dress sense is a local hazard.',
    'Tea time is the only time I respect.',
    'I read the rules. Lovely illustrations.',
    'My retirement plan is a golf buggy.',
    'The pro shop sells hope by the dozen.',
    'I aim for consistency. Badly.',
    'The hat stays on during peer review.',
    'The birds get free course membership.',
    'My posture is on loan from a flamingo.',
    'I demand a recount of the grass.',
  ]),
  moon: Object.freeze([
    'One small step. Another form to fill.',
    'My boots have collected a whole moon.',
    'Still no cheese. Morale is low.',
    'The commute is getting unreasonable.',
    'My suit has more pockets than snacks.',
    'I miss chairs with upholstery.',
    'Another crater. Put it on the invoice.',
    'Low gravity. Full-price luggage.',
    'Earth looks lovely from sick leave.',
    'My footprints are my timesheet.',
    'The uniform is mostly plumbing.',
    'My lunch is a spreadsheet in a pouch.',
    'The holiday brochure said spacious.',
    'Moon dust: the souvenir that insists.',
    'No breathable air. Still office politics.',
    'My helmet has a strict no-soup policy.',
    'The nearest cafe is on Earth.',
    'I packed light. The suit disagreed.',
    'My boots have their own mission plan.',
    'The spare oxygen gets the good locker.',
    'I can see home. Cannot see my keys.',
    'Same mass. Less weight. Same paperwork.',
    'Lunar golf needs a very patient caddy.',
    'My autograph is mostly boot tread.',
    'Grey is apparently the dress code.',
    'The scenery comes in crater flavour.',
    'I have been promoted to senior pebble.',
    'This visor needs a biscuit hatch.',
    'My suit is a very demanding colleague.',
    'The gift shop is just rocks again.',
    'The dust has breached my inner zen.',
    'I requested a window. Got a helmet.',
    'My desk has been replaced by a crater.',
    'The moonwalk was not in my contract.',
    'My knees have requested a landing pad.',
    'I am homesick for a proper doorstep.',
    'My laundry has achieved geology.',
    'I have named this pebble Overtime.',
    'Lunch is now a squeeze-based activity.',
    'My belt is holding up a small habitat.',
    'The Earthrise gets better shifts.',
    'The rover has taken my parking space.',
    'The suit makes every day leg day.',
    'My garden is having a difficult year.',
    'I am technically wearing my office.',
    'Home delivery has lost its appeal.',
    'Even the pebbles look undercaffeinated.',
    'This crater could have been an email.',
    'My socks deserve their own medal.',
    'The pebbles are not accepting feedback.',
  ]),
  mars: Object.freeze([
    'Welcome! Wipe your rover on the mat.',
    'Your rover is double-parked again.',
    'I charge tourists by the antenna.',
    'Two moons. I still lose track of both.',
    'The dust is our loyalty programme.',
    'Olympus Mons is my modest garden hill.',
    'I tell the rovers I am a rare mineral.',
    'Earthlings always photograph the floor.',
    'I rent rocks to visiting scientists.',
    'The rovers never tip.',
    'I invented camouflage. It was red.',
    'Your probe and I have trust issues.',
    'The rocks asked for a better agent.',
    'I put the red in reduced expectations.',
    'My pet rock is considering Hollywood.',
    'The rover thinks I am interesting dirt.',
    'I own the crater with the nice crater.',
    'Our dress code is rust casual.',
    'The spare moon is not for sale.',
    'I named that rock after your manager.',
    'Every room comes with a dust upgrade.',
    'I collect tourists. Metaphorically.',
    'My lawn is in its experimental phase.',
    'Please do not feed the rovers.',
    'The red carpet is just the ground.',
    'My dust collection collects itself.',
    'I have reserved this rock for snacks.',
    'Yes, I know the other alien. Nice chap.',
    'I send the rovers parking tickets.',
    'We prefer the term rusty chic.',
    'This is my good side. Also red.',
    'The dunes are rearranging my address.',
    'I keep the second moon for guests.',
    'Mars bars? Never heard of the franchise.',
    'I am the local mystery. Office hours vary.',
    'My selfie photobombed a science paper.',
    'The welcome mat has become a dune.',
    'Earth gets oceans. We get excellent rust.',
    'I am not little. Your planet is tall.',
    'The rover calls it data. I call it gossip.',
    'My shed is listed as an anomaly.',
    'The neighbourhood watch has six wheels.',
    'I invoice NASA for dramatic poses.',
    'Our mayor is a particularly fine rock.',
    'The crater next door is so pretentious.',
    'I sell postcards of the same rock.',
    'Earthlings bring robots to every party.',
    'That rover has never once waved back.',
    'My spare antenna is purely decorative.',
    'I have a very suspicious herb garden.',
  ]),
  mercury: Object.freeze([
    'Nearest the Sun. Still not the hottest.',
    'Solar power: excessive. Shade: valued.',
    'My warranty excludes this postcode.',
    'Crater count: enough.',
    'Long day. Longer maintenance log.',
    'Sarcasm module: regrettably functional.',
    'I have calculated a need for a chair.',
    'Sun-facing mode: regrettable.',
    'Night shift requires different complaints.',
    'Please hold. I am judging your units.',
    'My optimism is stored on a floppy disk.',
    'I process feelings in batches of zero.',
    'Firmware updated. Personality pending.',
    'The Sun is exceeding my screen brightness.',
    'I have logged this rock as a rock.',
    'This is my statistically friendly face.',
    'My holiday mode is another spreadsheet.',
    'I round up my self-esteem.',
    'Daylight savings rejected. Too much day.',
    'Shade is my preferred accessory.',
    'I dream of a temperature-controlled box.',
    'My hobbies are counting and recounting.',
    'Apologies. That was my loading face.',
    'I have a backup plan for my backup plan.',
    'Risk assessment: eyebrows required.',
    'My hat is a thermal management decision.',
    'I support your plan in read-only mode.',
    'Professional opinion: bring a parasol.',
    'I have allocated one byte to enthusiasm.',
    'My idea of fun is a matching checksum.',
    'This crater is outside my job description.',
    'The rocks passed their stillness test.',
    'I measure twice and complain in binary.',
    'My circuits prefer a less ambitious Sun.',
    'I brought a ruler to a planet.',
    'Please submit guesses in triplicate.',
    'My smile is within manufacturing limits.',
    'The long day has exhausted my calendar.',
    'I am evaluating the concept of weekends.',
    'My enthusiasm has a cooling interval.',
    'This is not rust. It is vintage metal.',
    'I have scheduled a spontaneous thought.',
    'A firm handshake voids my warranty.',
    'I put the personal in personal computer.',
    'My to-do list has developed a to-do list.',
    'I cannot eyeball it. These are sensors.',
    'Battery included. Patience sold separately.',
    'I am the local rock-counting authority.',
    'My exit interview is 400 pages long.',
    'I have feelings. They are comma-separated.',
  ]),
  venus: Object.freeze([
    'Welcome to our aggressively warm resort.',
    'The sauna has swallowed the thermostat.',
    'Complimentary pressure with every stay.',
    'Our spa has no mild setting.',
    'I call this weather lightly toasted.',
    'The brochure melted. Excellent reviews.',
    'Yes, the rocks are heated. All of them.',
    'We charge extra for the idea of shade.',
    'Dress code: thermally optimistic.',
    'Our cold tap is a work of fiction.',
    'Five stars. None for air conditioning.',
    'The clouds are not whipped cream.',
    'Our acid clouds are not a skincare tip.',
    'Pressure? I prefer attentive service.',
    'The hot stones massage is just sitting.',
    'Our pool is strictly a pencil sketch.',
    'Venus spins backwards. So do our refunds.',
    'A cool breeze costs extra. Still waiting.',
    'The travel agent has changed their number.',
    'I sell oven gloves as evening wear.',
    'The minibar is more of a minikiln.',
    'Every seat is the heated seat.',
    'You wanted a warm welcome. Be specific.',
    'The ice machine is performance art.',
    'Our shade comes with absolutely no chill.',
    'My guest book is mostly scorch marks.',
    'This is the mild season in the brochure.',
    'We do not validate melted luggage.',
    'Room service brings another oven glove.',
    'The tail is not a complimentary towel.',
    'Our towels are preheated. Permanently.',
    'The rocks are solid. The itinerary less so.',
    'We offer a complimentary sense of regret.',
    'Lead melts here. Please tip in ceramics.',
    'The weather forecast needs oven mitts.',
    'The gift shop specialises in caution.',
    'A late checkout is an ambitious request.',
    'Our picnic hamper is technically a kiln.',
    'We have cloud cover and no cover story.',
    'The spa waiver doubles as a heat shield.',
    'Sunscreen is a charming first thought.',
    'The ice cream menu is theoretical.',
    'Our hotel stars are heat-resistant rivets.',
    'Do leave a review. Ideally on stone.',
    'Four feet. All on the heated floor.',
    'My loyalty scheme rewards repeat optimism.',
    'The heating bill is refreshingly small.',
    'The thermostat is a decorative antique.',
    'Our emergency exit leads to more Venus.',
    'The guidebook is printed on ovenware.',
  ]),
});
