"""Package generated albedo maps as 2K textures and small overview maps.

Run with Pillow: python tools/prepare-orrery-textures.py PATH_TO_GENERATED_ORIGINALS
Only resampling/encoding happens here; source artwork is generated by imagegen.
"""
import json
import sys
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
originals = Path(sys.argv[1])
destination = root / 'src/assets/orrery'
destination.mkdir(parents=True, exist_ok=True)
for item in json.loads((root / 'tools/orrery-texture-sources.json').read_text()):
    source = Image.open(originals / item['source']).convert('RGB')
    for width, quality in [(512, 82), (2048, 91)]:
        target = destination / f"{item['id']}-{width}.webp"
        source.resize((width, width // 2), Image.Resampling.LANCZOS).save(target, quality=quality, method=6)
    print(item['id'])
